### ISSUE TITLE
Add three mandatory files for OSS

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/fresco-logistic-regression-2#3]
In order to properly release this repository we need three more files in the repository.

- [ ] `MAINTAINERS.md`
- [ ] `CONTRIBUTING.md`
- [ ] `LICENSE.md` 

See also:
https://github.com/philips-software/philips-howto-open-source
https://gitlab.ta.philips.com/open-source/howto-open-source#4-rules

**Comment by svdo** [comment]
Thanks for your vigilance, @JeroenKnoops! I added the missing files.
